namespace RKSoftware.Packages.ModelTransformer.Builders;

/// <summary>
/// 
/// </summary>
/// <param name="hostNamespace"></param>
/// <param name="className"></param>
/// <param name="methods"></param>
internal sealed class ExtensionClassCodeBuilder(string hostNamespace, string className, List<ExtensionMethodCodeBuilder> methods)
{
    public List<ExtensionMethodCodeBuilder> Methods { get; } = methods;

    public string Generate()
    {
        var methodsCode = string.Empty;
        if (Methods.Count > 0)
        {
            methodsCode = string.Join(Constants.NewLine, Methods.Select(m => m.Generate()));
        }

        var str = $@"
// <auto-generated>
#nullable enable

namespace {hostNamespace}
{{
{Constants.Indent1}public static partial class {className}
{Constants.Indent1}{{
{Constants.Indent_2}{methodsCode}
{Constants.Indent1}}}    
}}";
        return str;
    }
}
