namespace RKSoftware.Packages.ModelTransformer.Builders;

internal sealed class RegistrationAttributeCodeBuilder
{
    public const string Namespace = "RKSoftware.Packages.ModelTransformer.Attributes";
    public const string Name = "ModelTransformerRegistrationAttribute";
    public const string GenericName = $"{Name}<T1, T2>";


    public const string SourceCode = @$"
// <auto-generated>
#nullable enable

namespace {Namespace}
{{
    [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple=true)]
    public sealed class {GenericName} () : System.Attribute
    {{
        public string[]? {Constants.IgnoredProperties} {{ get; set; }}
    }}
}}";
}
