using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis;
using System.Collections.Concurrent;
using System.Diagnostics;

namespace RKSoftware.Packages.ModelTransformer.Tests;

public class SourceGeneratorTests
{
    private const string _directoryPath = "../../../../RKSoftware.Packages.ModelTransformer.Host/TestSamples/PrimitiveImplicit";
    private const string _initProgramText = @"
// <auto-generated>
#nullable enable

global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;

namespace RKSoftware.Packages.ModelTransformer
{
    public class Program
    {
        public static void Main(string[] args)
        {
        }
    }
}
";

    [Fact]
    public async Task TestCodeGeneration()
    {
        // Create the 'input' compilation that the generator will act on
        var inputCompilation = await CreateCompilation(_initProgramText);
        // directly create an instance of the generator
        // (Note: in the compiler this is loaded from an assembly, and created via reflection at runtime)
        var generator = new ModelTransformerIncrementalGenerator();

        // Create the driver that will control the generation, passing in our generator
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);

        // Run the generation pass
        // (Note: the generator driver itself is immutable, and all calls return an updated version of the driver that you should use for subsequent calls)
        driver = driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out var diagnostics);

        // We can now assert things about the resulting compilation:
        Debug.Assert(diagnostics.IsEmpty); // there were no diagnostics created by the generators
        Debug.Assert(outputCompilation.SyntaxTrees.Count() > 1); // we have two syntax trees, the original 'user' provided one, and the one added by the generator

        var d = outputCompilation.GetDiagnostics();
        //Debug.Assert(d.IsEmpty); // verify the compilation with the added source has no diagnostics

        // Or we can look at the results directly:
        var runResult = driver.GetRunResult();

        // The runResult contains the combined results of all generators passed to the driver
        Debug.Assert(runResult.GeneratedTrees.Length > 0);
        Debug.Assert(runResult.Diagnostics.IsEmpty);

        // Or you can access the individual results on a by-generator basis
        var generatorResult = runResult.Results[0];
        Debug.Assert(generatorResult.Diagnostics.IsEmpty);
        Debug.Assert(generatorResult.GeneratedSources.Length > 0);
        Debug.Assert(generatorResult.Exception is null);
    }

    private static async Task<CSharpCompilation> CreateCompilation(string source)
    {

        var files = Directory.GetFiles(_directoryPath, "*.cs", SearchOption.AllDirectories);
        var trees = new ConcurrentBag<SyntaxTree>([CSharpSyntaxTree.ParseText(source)]);
        await Parallel.ForEachAsync(files, async (x, ct) =>
        {
            var str = "#nullable enable" + Environment.NewLine + await File.ReadAllTextAsync(x, ct);

            var options = new CSharpParseOptions(LanguageVersion.Latest);
            var tree = CSharpSyntaxTree.ParseText(str, options: options, cancellationToken: ct, path: x);
            trees.Add(tree);
        });

        var references = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => !a.IsDynamic && !string.IsNullOrEmpty(a.Location))
            .Select(a => MetadataReference.CreateFromFile(a.Location))
            .ToList();

        return CSharpCompilation.Create("compilation",
                trees,
                references,
                new CSharpCompilationOptions(OutputKind.ConsoleApplication, nullableContextOptions: NullableContextOptions.Enable));
    }
}
