using Microsoft.CodeAnalysis;
using RKSoftware.Packages.ModelTransformer.Extensions;
using RKSoftware.Packages.ModelTransformer.Models;

namespace RKSoftware.Packages.ModelTransformer.Generations;

internal static class ModelExtensionGeneration
{
    private static readonly string _newLine = new('\n', 1);

    private static readonly string _indent1 = new('\t', 1);
    private static readonly string _indent2 = new('\t', 2);
    private static readonly string _indent3 = new('\t', 3);
    private static readonly string _indent4 = new('\t', 4);
    private static readonly string _indent5 = new('\t', 5);

    public static string GenerateExtensionClass(string hostNamespace, string className, List<string> methods)
    {
        var methodsCode = string.Empty;
        if (methods.Count > 0)
        {
            methodsCode = string.Join(_newLine, methods);
        }

        var str = $@"
// <auto-generated>
#nullable enable

namespace {hostNamespace}
{{
{_indent1}public static partial class {className}
{_indent1}{{
{_indent2}{methodsCode}
{_indent1}}}    
}}";
        return str;
    }


    public static string GenerateExtensionMethod(AttributeDataModel attr, Dictionary<string, List<AttributeDataModel>> dic)
    {
        var variableCreationCode = string.Empty;
        var methodsCode = string.Empty;
        var constructorVariableMappingCode = string.Empty;
        var postConstructorVariableMappingCode = string.Empty;
        var variableMappingCode = string.Empty;

        var mappings = GeneratePropertyMappings(attr, dic);

        if (mappings.Count > 0)
        {
            var variableCreations = mappings
                .Select(x => x.VariableCreationCode)
                .Where(x => !string.IsNullOrWhiteSpace(x))
                .ToList();

            if (variableCreations.Count > 0)
            {
                variableCreationCode = $"{_newLine}{string.Join($"{_newLine}{_newLine}", variableCreations)}{_newLine}";
            }

            var constructorVariableMappings = mappings
                .Select(x => x.ConstructorVariableMappingCode)
                .Where(x => !string.IsNullOrWhiteSpace(x))
                .ToList();

            if (constructorVariableMappings.Count > 0)
            {
                constructorVariableMappingCode = $"{_newLine}{string.Join($",{_newLine}", constructorVariableMappings)}";
            }

            var postConstructorVariableMappings = mappings
                .Select(x => x.PostConstructorVariableMappingCode)
                .Where(x => !string.IsNullOrWhiteSpace(x))
                .ToList();

            if (postConstructorVariableMappings.Count > 0)
            {
                postConstructorVariableMappingCode = string.Join($",{_newLine}", postConstructorVariableMappings);
            }

            var variableMappings = mappings
                .Select(x => x.VariableMappingCode)
                .Where(x => !string.IsNullOrWhiteSpace(x))
                .ToList();

            if (variableMappings.Count > 0)
            {
                variableMappingCode = string.Join($"{_newLine}", variableMappings);
            }

            var methods = mappings
                .Select(x => x.MethodCode)
                .Where(x => !string.IsNullOrWhiteSpace(x))
                .ToList();

            if (methods.Count > 0)
            {
                methodsCode = $"{_newLine}{string.Join($"{_newLine}{_newLine}", methods)}{_newLine}";
            }
        }

        var str = $@"
{_indent2}#region to {attr.Target.Name}

{_indent2}public static {attr.Target.ToDisplayString()} Transform (this {attr.Source.ToDisplayString()} source, {attr.Target.ToDisplayString()}? target = null)
{_indent2}{{
{_indent3}if (source == null) 
{_indent3}{{
{_indent4}throw new System.ArgumentNullException(nameof(source));
{_indent3}}}
{variableCreationCode}
{_indent3}if (target == null)
{_indent3}{{
{_indent4}target = new {attr.Target.ToDisplayString()} ({constructorVariableMappingCode})
{_indent4}{{
{postConstructorVariableMappingCode}
{_indent4}}};
{_indent3}}}
{_indent3}else
{_indent3}{{
{variableMappingCode}
{_indent3}}}
{_indent3}return target;
{_indent2}}}
{methodsCode}
{_indent2}#endregion
";
        return str;
    }

    #region helpers

    private static List<PropertyMappingModel> GeneratePropertyMappings(AttributeDataModel attr, Dictionary<string, List<AttributeDataModel>> dic)
    {
        var mappings = new List<PropertyMappingModel>();

        var targetProps = attr.TargetProperties;

        foreach (var targetProp in targetProps)
        {
            IPropertySymbol? sourceProp = null;
            string? mappingCode = null;

            var isIgnored = attr.IgnoredProperties.TryGetValue(targetProp.Key, out _);

            var mapping = new PropertyMappingModel(targetProp.Value, attr, isIgnored);

            if (!isIgnored)
            {
                if (attr.SourceProperties.TryGetValue(targetProp.Key, out sourceProp))
                {
                    if (sourceProp.CanNotConvertType(targetProp.Value))
                    {
                        if (dic.TryGetValue(sourceProp.Type.OriginalDefinition.ToDisplayString(), out var complexTargets) &&
                            complexTargets.Any(x => SymbolEqualityComparer.Default.Equals(x.Target, targetProp.Value.Type)))
                        {
                            mappingCode = $"source.{sourceProp.Name}{(sourceProp.IsNullable() ? "?" : "")}.Transform(({mapping.PropertyType.OriginalDefinition.ToDisplayString()}?)null)";
                        }
                        else
                        {
                            var sourceArgumentType = sourceProp.GetGenericArgumentType();
                            var targetArgumentType = targetProp.Value.GetGenericArgumentType();
                            if (sourceArgumentType != null &&
                                targetArgumentType != null &&
                                (targetArgumentType.IsNullable() || !sourceArgumentType.IsNullable()))
                            {
                                string? str = null;

                                if (dic.TryGetValue(sourceArgumentType.OriginalDefinition.ToDisplayString(), out var complexArgumentTargets) &&
                                    complexArgumentTargets.Any(x => SymbolEqualityComparer.Default.Equals(x.Target, targetArgumentType)))
                                {
                                    if (mapping.PropertyType is INamedTypeSymbol nt && nt.Constructors.Any(c => c.Parameters.Length > 0))
                                    {
                                        str = $"new (source.{sourceProp.Name}.Select(x => x.Transform(({targetArgumentType.OriginalDefinition.ToDisplayString()}?)null)))";
                                    }
                                    else if (mapping.PropertyType.IsGenericInterfaceConstructable() || mapping.PropertyType.IsArrayType())
                                    {
                                        str = $"[.. source.{sourceProp.Name}.Select(x => x{(sourceArgumentType.IsNullable() ? "?" : "")}.Transform(({targetArgumentType.OriginalDefinition.ToDisplayString()}?)null))]";
                                    }
                                } 
                                else if(sourceArgumentType.IsPrimitiveOrString() && 
                                        targetArgumentType.IsPrimitiveOrString() &&
                                        SymbolEqualityComparer.Default.Equals(sourceArgumentType, targetArgumentType))
                                {
                                    if (mapping.PropertyType is INamedTypeSymbol nt && nt.Constructors.Any(c => c.Parameters.Length > 0))
                                    {
                                        str = $"source.{sourceProp.Name}[..]";
                                    }
                                    else if (mapping.PropertyType.IsGenericInterfaceConstructable())
                                    {
                                        if (mapping.PropertyType is INamedTypeSymbol nts &&
                                            nts.IsListInterfaceSpecial())
                                        {
                                            str = $"source.{sourceProp.Name}.ToList()";
                                        }
                                        else
                                        {
                                            str = $"source.{sourceProp.Name}.ToArray()";
                                        }
                                    }
                                    else if (mapping.PropertyType.IsArrayType())
                                    {
                                        str = $"source.{sourceProp.Name}[..]";
                                    }
                                }

                                if (str != null)
                                {
                                    mappingCode = sourceProp.IsNullable() ? $"source.{sourceProp.Name} != null ? {str} : default" : str;
                                }
                            }
                        }
                    }
                    else
                    {
                        mappingCode = $"source.{sourceProp.Name}";
                    }
                }
            }

            if (!isIgnored)
            {
                if (mappingCode != null)
                {
                    mapping.VariableCreationCode = CreateVariableByDefaultMappingMethod(mapping);
                }
                else
                {
                    mapping.VariableCreationCode = CreateVariableByRequiredMappingMethod(mapping);
                }
            }

            if (mapping.IsConstructorParam)
            {
                mapping.ConstructorVariableMappingCode = SetVariableInConstructor(mapping);
            }
            else
            {
                mapping.PostConstructorVariableMappingCode = SetVariablePostConstructor(mapping);
            }

            if (!mapping.IsReadonly && !isIgnored)
            {
                mapping.VariableMappingCode = SetVariable(mapping);
            }

            if (!isIgnored)
            {
                if (mappingCode != null)
                {
                    var defaultMethod = CreateDefaultMappingMethod(mapping, attr, mappingCode);
                    var optionalMethod = CreateOptionalMappingMethodToBeImplemented(mapping, attr);
                    mapping.MethodCode = $"{defaultMethod}{_newLine}{optionalMethod}";
                }
                else
                {
                    mapping.MethodCode = CreateRequiredMappingMethodToBeImplemented(mapping, attr);
                }
            }

            mappings.Add(mapping);
        }

        return mappings;
    }
    #endregion

    private static string CreateVariableByDefaultMappingMethod(PropertyMappingModel mapping)
    {
        return
@$"{_indent3}var {mapping.VariableName} = {mapping.DefaultMethodName}(source);
{_indent3}{mapping.MethodName}(source, ref {mapping.VariableName});";
    }

    private static string CreateVariableByRequiredMappingMethod(PropertyMappingModel mapping)
    {
        return @$"{_indent3}var {mapping.VariableName} = {mapping.MethodName}(source);";
    }

    private static string SetVariableInConstructor(PropertyMappingModel mapping)
    {
        return $@"{_indent5}{mapping.PropertyName} : {mapping.VariableName}";
    }

    private static string SetVariablePostConstructor(PropertyMappingModel mapping)
    {
        return $@"{_indent5}{mapping.PropertyName} = {mapping.VariableName}";
    }

    private static string SetVariable(PropertyMappingModel mapping)
    {
        return $@"{_indent4}target.{mapping.PropertyName} = {mapping.VariableName};";
    }

    private static string CreateDefaultMappingMethod(PropertyMappingModel mapping, AttributeDataModel attr, string code)
    {
        return
$@"{_indent2}private static {mapping.PropertyType.ToDisplayString()} {mapping.DefaultMethodName}({attr.Source.ToDisplayString()} source)
{_indent2}{{
{_indent3}return {code};
{_indent2}}}";
    }

    private static string CreateOptionalMappingMethodToBeImplemented(PropertyMappingModel mapping, AttributeDataModel attr)
    {
        return
$@"{_indent2}static partial void {mapping.MethodName}({attr.Source.ToDisplayString()} source, ref {mapping.PropertyType.ToDisplayString()} target);";
    }

    private static string CreateRequiredMappingMethodToBeImplemented(PropertyMappingModel mapping, AttributeDataModel attr)
    {
        return
$@"{_indent2}private static partial {mapping.PropertyType.ToDisplayString()} {mapping.MethodName}({attr.Source.ToDisplayString()} source);";
    }
}
