namespace RKSoftware.Packages.ModelTransformer.Generations;

internal static class RegistrationAttributeGeneration
{
    public const string Namespace = "RKSoftware.Packages.ModelTransformer.Attributes";
    public const string Name = "ModelTransformerRegistrationAttribute";
    public const string GenericName = $"{Name}<T1, T2>";
    public const string IgnoredPropertiesParameterName = "ignoredProperties";

    public const string SourceCode = @$"
// <auto-generated>
#nullable enable

namespace {Namespace}
{{
    [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple=true)]
#pragma warning disable CS9113
    public sealed class {GenericName} (params string[] ignoredProperties) : System.Attribute
#pragma warning restore CS9113
    {{
    }}
}}";
}
