namespace RKSoftware.Packages.ModelTransformer.Generations;

internal static class RegistrationAttributeGeneration
{
    public const string Namespace = "RKSoftware.Packages.ModelTransformer.Attributes";
    public const string Name = "ModelTransformerRegistrationAttribute";
    public const string GenericName = $"{Name}<T1, T2>";
    public const string IgnoredPropertiesParameterName = "ignoredProperties";

    public const string SourceCode = @$"
// <auto-generated>
#nullable enable

using System.Collections.Generic;
using System.Collections.Frozen;

namespace {Namespace}
{{
    [System.AttributeUsage(System.AttributeTargets.Class)]
    public sealed class {GenericName} (params string[] ignoredProperties) : System.Attribute
    {{
    }}
}}";
}
