namespace RKSoftware.Packages.ModelTransformer;

internal static class ModelTransformerIncrementalGeneratorHelper
{
    public const string Attribute = @"
// <auto-generated>
#nullable enable

namespace RKSoftware.Packages.ModelTransformer
{
    [System.AttributeUsage(System.AttributeTargets.Class)]
    public sealed class ModelTransformerRegistrationAttribute<T1, T2> : System.Attribute
    {
    }
}";
}
